//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.33440。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class Version {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Parameters {
    
    private ParametersParameter[] parameterField;
    
    private ParametersWarnings[] warningsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ParametersParameter[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Warnings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ParametersWarnings[] Warnings {
        get {
            return this.warningsField;
        }
        set {
            this.warningsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ParametersParameter {
    
    private string nameField;
    
    private string valueField;
    
    private string unitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ParametersWarnings {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MeasurementResultData {
    
    private string plateField;
    
    private MeasurementResultDataHeader[] headerField;
    
    private MeasurementResultDataScript[] scriptField;
    
    private MeasurementResultDataSection[] sectionField;
    
    private string dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Plate {
        get {
            return this.plateField;
        }
        set {
            this.plateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementResultDataHeader[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Script", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementResultDataScript[] Script {
        get {
            return this.scriptField;
        }
        set {
            this.scriptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Section", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementResultDataSection[] Section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataHeader {
    
    private Version[][] software_VersionsField;
    
    private MeasurementResultDataHeaderInstrument[] instrumentField;
    
    private Version[][] hardware_VersionsField;
    
    private Parameters[] parametersField;
    
    private string applicationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Version", typeof(Version))]
    public Version[][] Software_Versions {
        get {
            return this.software_VersionsField;
        }
        set {
            this.software_VersionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Instrument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementResultDataHeaderInstrument[] Instrument {
        get {
            return this.instrumentField;
        }
        set {
            this.instrumentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Version", typeof(Version))]
    public Version[][] Hardware_Versions {
        get {
            return this.hardware_VersionsField;
        }
        set {
            this.hardware_VersionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameters")]
    public Parameters[] Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataHeaderInstrument {
    
    private string nameField;
    
    private string serialNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataScript {
    
    private TecanMeasurement tecanMeasurementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="tecan.at.schema.documents")]
    public TecanMeasurement TecanMeasurement {
        get {
            return this.tecanMeasurementField;
        }
        set {
            this.tecanMeasurementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="tecan.at.schema.documents", IsNullable=false)]
public partial class TecanMeasurement {
    
    private TecanMeasurementMeasurementManualCycle[] measurementManualCycleField;
    
    private TecanMeasurementMeasurementInfo[] measurementInfoField;
    
    private string idField;
    
    private string classField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeasurementManualCycle")]
    public TecanMeasurementMeasurementManualCycle[] MeasurementManualCycle {
        get {
            return this.measurementManualCycleField;
        }
        set {
            this.measurementManualCycleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeasurementInfo")]
    public TecanMeasurementMeasurementInfo[] MeasurementInfo {
        get {
            return this.measurementInfoField;
        }
        set {
            this.measurementInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycle {
    
    private TecanMeasurementMeasurementManualCycleCyclePlate[] cyclePlateField;
    
    private string idField;
    
    private string numberField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CyclePlate")]
    public TecanMeasurementMeasurementManualCycleCyclePlate[] CyclePlate {
        get {
            return this.cyclePlateField;
        }
        set {
            this.cyclePlateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlate {
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRange[] plateRangeField;
    
    private string idField;
    
    private string fileField;
    
    private string plateWithCoverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PlateRange")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRange[] PlateRange {
        get {
            return this.plateRangeField;
        }
        set {
            this.plateRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string plateWithCover {
        get {
            return this.plateWithCoverField;
        }
        set {
            this.plateWithCoverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRange {
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbance[] measurementAbsorbanceField;
    
    private string idField;
    
    private string rangeField;
    
    private string autoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeasurementAbsorbance")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbance[] MeasurementAbsorbance {
        get {
            return this.measurementAbsorbanceField;
        }
        set {
            this.measurementAbsorbanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string range {
        get {
            return this.rangeField;
        }
        set {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string auto {
        get {
            return this.autoField;
        }
        set {
            this.autoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbance {
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWell[] wellField;
    
    private string idField;
    
    private string modeField;
    
    private string typeField;
    
    private string nameField;
    
    private string longnameField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Well")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWell[] Well {
        get {
            return this.wellField;
        }
        set {
            this.wellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longname {
        get {
            return this.longnameField;
        }
        set {
            this.longnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWell {
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReading[] measurementReadingField;
    
    private string idField;
    
    private string autoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeasurementReading")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReading[] MeasurementReading {
        get {
            return this.measurementReadingField;
        }
        set {
            this.measurementReadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string auto {
        get {
            return this.autoField;
        }
        set {
            this.autoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReading {
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabel[] readingLabelField;
    
    private string idField;
    
    private string nameField;
    
    private string beamDiameterField;
    
    private string beamGridTypeField;
    
    private string beamGridSizeField;
    
    private string beamEdgeDistanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReadingLabel")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabel[] ReadingLabel {
        get {
            return this.readingLabelField;
        }
        set {
            this.readingLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string beamDiameter {
        get {
            return this.beamDiameterField;
        }
        set {
            this.beamDiameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string beamGridType {
        get {
            return this.beamGridTypeField;
        }
        set {
            this.beamGridTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string beamGridSize {
        get {
            return this.beamGridSizeField;
        }
        set {
            this.beamGridSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string beamEdgeDistance {
        get {
            return this.beamEdgeDistanceField;
        }
        set {
            this.beamEdgeDistanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabel {
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingSettings[] readingSettingsField;
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingTime[] readingTimeField;
    
    private TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingFilter[] readingFilterField;
    
    private string idField;
    
    private string nameField;
    
    private string scanTypeField;
    
    private string refIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReadingSettings")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingSettings[] ReadingSettings {
        get {
            return this.readingSettingsField;
        }
        set {
            this.readingSettingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReadingTime")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingTime[] ReadingTime {
        get {
            return this.readingTimeField;
        }
        set {
            this.readingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReadingFilter")]
    public TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingFilter[] ReadingFilter {
        get {
            return this.readingFilterField;
        }
        set {
            this.readingFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scanType {
        get {
            return this.scanTypeField;
        }
        set {
            this.scanTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID {
        get {
            return this.refIDField;
        }
        set {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingSettings {
    
    private string numberField;
    
    private string rateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingTime {
    
    private string integrationTimeField;
    
    private string lagTimeField;
    
    private string readDelayField;
    
    private string flashField;
    
    private string darkField;
    
    private string excitationTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string integrationTime {
        get {
            return this.integrationTimeField;
        }
        set {
            this.integrationTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lagTime {
        get {
            return this.lagTimeField;
        }
        set {
            this.lagTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string readDelay {
        get {
            return this.readDelayField;
        }
        set {
            this.readDelayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string flash {
        get {
            return this.flashField;
        }
        set {
            this.flashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dark {
        get {
            return this.darkField;
        }
        set {
            this.darkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string excitationTime {
        get {
            return this.excitationTimeField;
        }
        set {
            this.excitationTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementManualCycleCyclePlatePlateRangeMeasurementAbsorbanceWellMeasurementReadingReadingLabelReadingFilter {
    
    private string idField;
    
    private string typeField;
    
    private string wavelengthField;
    
    private string bandwidthField;
    
    private string attenuationField;
    
    private string usageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wavelength {
        get {
            return this.wavelengthField;
        }
        set {
            this.wavelengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bandwidth {
        get {
            return this.bandwidthField;
        }
        set {
            this.bandwidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string attenuation {
        get {
            return this.attenuationField;
        }
        set {
            this.attenuationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementInfo {
    
    private TecanMeasurementMeasurementInfoScriptTemplateSettings[] scriptTemplateSettingsField;
    
    private string idField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ScriptTemplateSettings")]
    public TecanMeasurementMeasurementInfoScriptTemplateSettings[] ScriptTemplateSettings {
        get {
            return this.scriptTemplateSettingsField;
        }
        set {
            this.scriptTemplateSettingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementInfoScriptTemplateSettings {
    
    private TecanMeasurementMeasurementInfoScriptTemplateSettingsScriptTemplateGeneralSettings[] scriptTemplateGeneralSettingsField;
    
    private TecanMeasurementMeasurementInfoScriptTemplateSettingsScriptTemplateDescriptionSettings[] scriptTemplateDescriptionSettingsField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ScriptTemplateGeneralSettings")]
    public TecanMeasurementMeasurementInfoScriptTemplateSettingsScriptTemplateGeneralSettings[] ScriptTemplateGeneralSettings {
        get {
            return this.scriptTemplateGeneralSettingsField;
        }
        set {
            this.scriptTemplateGeneralSettingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ScriptTemplateDescriptionSettings")]
    public TecanMeasurementMeasurementInfoScriptTemplateSettingsScriptTemplateDescriptionSettings[] ScriptTemplateDescriptionSettings {
        get {
            return this.scriptTemplateDescriptionSettingsField;
        }
        set {
            this.scriptTemplateDescriptionSettingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementInfoScriptTemplateSettingsScriptTemplateGeneralSettings {
    
    private string idField;
    
    private string titleField;
    
    private string groupField;
    
    private string infoField;
    
    private string imageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="tecan.at.schema.documents")]
public partial class TecanMeasurementMeasurementInfoScriptTemplateSettingsScriptTemplateDescriptionSettings {
    
    private string idField;
    
    private string internalField;
    
    private string externalField;
    
    private string isExternalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Internal {
        get {
            return this.internalField;
        }
        set {
            this.internalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string External {
        get {
            return this.externalField;
        }
        set {
            this.externalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsExternal {
        get {
            return this.isExternalField;
        }
        set {
            this.isExternalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataSection {
    
    private string time_StartField;
    
    private string time_EndField;
    
    private Parameters[] parametersField;
    
    private MeasurementResultDataSectionData[] dataField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time_Start {
        get {
            return this.time_StartField;
        }
        set {
            this.time_StartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time_End {
        get {
            return this.time_EndField;
        }
        set {
            this.time_EndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameters")]
    public Parameters[] Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementResultDataSectionData[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataSectionData {
    
    private MeasurementResultDataSectionDataWell[] wellField;
    
    private string cycleField;
    
    private string temperatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Well", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementResultDataSectionDataWell[] Well {
        get {
            return this.wellField;
        }
        set {
            this.wellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Cycle {
        get {
            return this.cycleField;
        }
        set {
            this.cycleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataSectionDataWell {
    
    private MeasurementResultDataSectionDataWellSingle[] singleField;
    
    private string posField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Single", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public MeasurementResultDataSectionDataWellSingle[] Single {
        get {
            return this.singleField;
        }
        set {
            this.singleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeasurementResultDataSectionDataWellSingle {
    
    private string labelIdField;
    
    private string statusField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LabelId {
        get {
            return this.labelIdField;
        }
        set {
            this.labelIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeasurementResultData", typeof(MeasurementResultData))]
    [System.Xml.Serialization.XmlElementAttribute("Parameters", typeof(Parameters))]
    [System.Xml.Serialization.XmlElementAttribute("Version", typeof(Version), IsNullable=true)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
